# -*- coding: utf-8 -*-
"""fakenews_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAYEZ6dGZXdmcT55toTLyw9X06EodZKp

# Fake News Detection with BERT and Explainability Analysis
"""

!pip install datasets transformers shap lime -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

from datasets import load_dataset

dataset = load_dataset("GonzaloA/fake_news")
print(dataset)

df_train = pd.DataFrame(dataset['train'])
df_test = pd.DataFrame(dataset['test'])

print(df_train.head())
print(df_train['label'].value_counts())
print(f"\n훈련 데이터 크기: {len(df_train)}")
print(f"테스트 데이터 크기: {len(df_test)}")

# 결측값 확인
print("결측값:")
print(df_train.isnull().sum())

# 결측값 제거
df_train = df_train.dropna(subset=['title', 'text', 'label'])
df_test = df_test.dropna(subset=['title', 'text', 'label'])

# title + text 합쳐서 하나의 컬럼으로
df_train['content'] = df_train['title'] + ' ' + df_train['text']
df_test['content'] = df_test['title'] + ' ' + df_test['text']

# 텍스트 길이 분포
df_train['text_len'] = df_train['content'].apply(len)

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

# 라벨 분포
axes[0].bar(['Real (0)', 'Fake (1)'], df_train['label'].value_counts().sort_index(), color=['steelblue', 'tomato'])
axes[0].set_title('Label Distribution')
axes[0].set_ylabel('Count')

# 텍스트 길이 분포
df_train[df_train['label']==0]['text_len'].hist(ax=axes[1], alpha=0.6, bins=50, color='steelblue', label='Real')
df_train[df_train['label']==1]['text_len'].hist(ax=axes[1], alpha=0.6, bins=50, color='tomato', label='Fake')
axes[1].set_title('Text Length Distribution')
axes[1].set_xlabel('Character Count')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"\n평균 텍스트 길이:")
print(df_train.groupby('label')['text_len'].mean())

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# TF-IDF 벡터화
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2), sublinear_tf=True)
X_train = tfidf.fit_transform(df_train['content'])
X_test = tfidf.transform(df_test['content'])

y_train = df_train['label']
y_test = df_test['label']

# Logistic Regression
lr = LogisticRegression(max_iter=1000, C=1.0)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

print("=== TF-IDF + Logistic Regression ===")
print(classification_report(y_test, y_pred_lr, target_names=['Real', 'Fake']))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Real', 'Fake'],
            yticklabels=['Real', 'Fake'])
plt.title('TF-IDF + LR Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from sklearn.metrics import classification_report
import torch

# 데이터 샘플링 (T4 메모리 고려)
train_sample = df_train.sample(n=10000, random_state=42)
test_sample = df_test.sample(n=2000, random_state=42)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

class FakeNewsDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=256):
        self.texts = texts.reset_index(drop=True)
        self.labels = labels.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'label': torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_dataset = FakeNewsDataset(train_sample['content'], train_sample['label'], tokenizer)
test_dataset = FakeNewsDataset(test_sample['content'], test_sample['label'], tokenizer)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

# 모델
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
model = model.to(device)

# 옵티마이저 & 스케줄러
optimizer = AdamW(model.parameters(), lr=2e-5)
total_steps = len(train_loader) * 3
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

print("설정 완료! 학습 시작 준비됐어요.")
print(f"훈련 샘플: {len(train_sample)}, 테스트 샘플: {len(test_sample)}")
print(f"배치당 스텝 수: {len(train_loader)}")

# 학습 함수
def train_epoch(model, loader, optimizer, scheduler, device):
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

    return total_loss / len(loader)

# 평가 함수
def evaluate(model, loader, device):
    model.eval()
    preds, true_labels = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            preds.extend(torch.argmax(logits, dim=1).cpu().numpy())
            true_labels.extend(labels.cpu().numpy())

    return preds, true_labels

# 학습 루프 (3 epochs)
for epoch in range(3):
    avg_loss = train_epoch(model, train_loader, optimizer, scheduler, device)
    preds, true_labels = evaluate(model, test_loader, device)
    print(f"\nEpoch {epoch+1}/3 | Loss: {avg_loss:.4f}")
    print(classification_report(true_labels, preds, target_names=['Real', 'Fake']))

import os

# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 저장 경로
save_path = '/content/drive/MyDrive/fakenews_bert'
os.makedirs(save_path, exist_ok=True)

# 모델 & 토크나이저 저장
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

# 데이터 저장
train_sample.to_csv(f'{save_path}/train_sample.csv', index=False)
test_sample.to_csv(f'{save_path}/test_sample.csv', index=False)

print(f"저장 완료! 경로: {save_path}")

import shap
import transformers

# SHAP용 파이프라인 생성
pipe = transformers.pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    device=0,
    return_all_scores=True
)

# 샘플 텍스트 준비 (진짜 5개, 가짜 5개)
real_samples = test_sample[test_sample['label']==0]['content'].head(5).tolist()
fake_samples = test_sample[test_sample['label']==1]['content'].head(5).tolist()
samples = real_samples + fake_samples

# 텍스트 길이 제한 (SHAP 속도 위해)
samples = [s[:512] for s in samples]

# SHAP explainer
explainer = shap.Explainer(pipe)
shap_values = explainer(samples)

print("SHAP 계산 완료!")

# 전체 테스트셋에서 오분류 케이스 추출
model.eval()
all_preds, all_labels, all_texts = [], [], []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

test_sample_reset = test_sample.reset_index(drop=True)
test_sample_reset['pred'] = all_preds
test_sample_reset['true'] = all_labels

# 오분류 케이스
misclassified = test_sample_reset[test_sample_reset['pred'] != test_sample_reset['true']]
print(f"전체 테스트: {len(test_sample_reset)}개")
print(f"오분류: {len(misclassified)}개 ({len(misclassified)/len(test_sample_reset)*100:.1f}%)")
print(f"\n오분류 유형:")
print(f"진짜->가짜 (False Positive): {len(misclassified[misclassified['true']==0])}개")
print(f"가짜->진짜 (False Negative): {len(misclassified[misclassified['true']==1])}개")

# 오분류 샘플 확인
print("\n=== 오분류 샘플 예시 ===")
for _, row in misclassified.head(3).iterrows():
    print(f"\n실제: {'Real' if row['true']==0 else 'Fake'} | 예측: {'Real' if row['pred']==0 else 'Fake'}")
    print(f"텍스트: {row['content'][:300]}...")
    print("-"*50)

# 오분류 패턴 분석
from collections import Counter
import re

def get_top_words(texts, n=20):
    words = []
    for text in texts:
        words.extend(re.findall(r'\b[a-zA-Z]{4,}\b', text.lower()))
    stopwords = {'that', 'this', 'with', 'have', 'from', 'they', 'will', 'been', 'were', 'when', 'what', 'said', 'about', 'would', 'their', 'there', 'which', 'also'}
    words = [w for w in words if w not in stopwords]
    return Counter(words).most_common(n)

fp_texts = misclassified[misclassified['true']==0]['content'].tolist()
fn_texts = misclassified[misclassified['true']==1]['content'].tolist()

print("=== 진짜->가짜 오분류에서 자주 나온 단어 (False Positive) ===")
for word, count in get_top_words(fp_texts):
    print(f"  {word}: {count}")

print("\n=== 가짜->진짜 오분류에서 자주 나온 단어 (False Negative) ===")
for word, count in get_top_words(fn_texts):
    print(f"  {word}: {count}")

# 오분류 vs 정분류 텍스트 길이 비교
correct = test_sample_reset[test_sample_reset['pred'] == test_sample_reset['true']]

print(f"\n=== 텍스트 길이 비교 ===")
print(f"정분류 평균 길이: {correct['content'].apply(len).mean():.0f}")
print(f"오분류 평균 길이: {misclassified['content'].apply(len).mean():.0f}")

print(f"\n오분류 중 짧은 텍스트 (1000자 미만): {len(misclassified[misclassified['content'].apply(len) < 1000])}개")
print(f"오분류 중 긴 텍스트 (1000자 이상): {len(misclassified[misclassified['content'].apply(len) >= 1000])}개")

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. 오분류 유형 비교
categories = ['False Positive\n(Real->Fake)', 'False Negative\n(Fake->Real)']
counts = [7, 14]
colors = ['steelblue', 'tomato']
axes[0].bar(categories, counts, color=colors)
axes[0].set_title('Misclassification Types')
axes[0].set_ylabel('Count')
for i, v in enumerate(counts):
    axes[0].text(i, v + 0.2, str(v), ha='center', fontweight='bold')

# 2. 텍스트 길이 비교
length_data = {
    'Correct': correct['content'].apply(len).values,
    'Misclassified': misclassified['content'].apply(len).values
}
axes[1].boxplot(length_data.values(), labels=length_data.keys())
axes[1].set_title('Text Length: Correct vs Misclassified')
axes[1].set_ylabel('Character Count')

# 3. 상위 키워드 비교
fp_words = dict(get_top_words(fp_texts, 8))
fn_words = dict(get_top_words(fn_texts, 8))
all_words = list(set(list(fp_words.keys()) + list(fn_words.keys())))[:10]

x = np.arange(len(all_words))
width = 0.35
fp_vals = [fp_words.get(w, 0) for w in all_words]
fn_vals = [fn_words.get(w, 0) for w in all_words]

axes[2].bar(x - width/2, fp_vals, width, label='False Positive', color='steelblue', alpha=0.8)
axes[2].bar(x + width/2, fn_vals, width, label='False Negative', color='tomato', alpha=0.8)
axes[2].set_xticks(x)
axes[2].set_xticklabels(all_words, rotation=45, ha='right')
axes[2].set_title('Top Keywords in Misclassified Samples')
axes[2].set_ylabel('Frequency')
axes[2].legend()

plt.suptitle('Fake News Detection: Error Analysis', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n=== 최종 요약 ===")
print(f"TF-IDF + LR 정확도: 97%")
print(f"BERT 정확도: 99%")
print(f"오분류 21개 중 정치 관련 키워드 포함 비율: {sum(1 for t in misclassified['content'] if any(w in t.lower() for w in ['trump', 'clinton', 'hillary', 'election']))/len(misclassified)*100:.0f}%")
print(f"오분류 평균 텍스트 길이: {misclassified['content'].apply(len).mean():.0f}자 (정분류 대비 +{misclassified['content'].apply(len).mean() - correct['content'].apply(len).mean():.0f}자)")

# 1. 오분류 분석 결과 CSV 저장
misclassified.to_csv('/content/drive/MyDrive/fakenews_bert/misclassified_analysis.csv', index=False)
test_sample_reset.to_csv('/content/drive/MyDrive/fakenews_bert/test_results.csv', index=False)

# 2. 시각화 이미지 저장
fig.savefig('/content/drive/MyDrive/fakenews_bert/error_analysis.png', dpi=150, bbox_inches='tight')

# 3. 결과 요약 텍스트 저장
summary = f"""
=== Fake News Detection Project Summary ===

Dataset: GonzaloA/fake_news
Train: 10,000 samples / Test: 2,000 samples

Model Comparison:
- TF-IDF + Logistic Regression: 97% accuracy
- BERT fine-tuned: 99% accuracy

Error Analysis (21 misclassified):
- False Positive (Real->Fake): 7
- False Negative (Fake->Real): 14
- Average text length (correct): {correct['content'].apply(len).mean():.0f}
- Average text length (misclassified): {misclassified['content'].apply(len).mean():.0f}

Key Findings:
- Political content (trump, clinton, election) shows higher misclassification rate
- Fake news using professional vocabulary tends to evade detection
- Longer texts are harder to classify correctly
- Model shows lexical bias over contextual understanding
"""

with open('/content/drive/MyDrive/fakenews_bert/summary.txt', 'w') as f:
    f.write(summary)

print("모두 저장 완료!")
print("저장 위치: Google Drive > fakenews_bert 폴더")

